/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    BalanceBars: typeof import('./src/components/BalanceBars.vue')['default']
    BottomTabs: typeof import('./src/components/BottomTabs.vue')['default']
    CheckInCard: typeof import('./src/components/CheckInCard.vue')['default']
    DashGrid: typeof import('./src/components/DashGrid.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DateField: typeof import('./src/components/DateField.vue')['default']
    EditDialog: typeof import('./src/components/EditDialog.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    FieldRow: typeof import('./src/components/FieldRow.vue')['default']
    IdentityBand: typeof import('./src/components/IdentityBand.vue')['default']
    MonthCalendar: typeof import('./src/components/MonthCalendar.vue')['default']
    PageBody: typeof import('./src/components/PageBody.vue')['default']
    PageHead: typeof import('./src/components/PageHead.vue')['default']
    PersonRow: typeof import('./src/components/PersonRow.vue')['default']
    RequestDialog: typeof import('./src/components/RequestDialog.vue')['default']
    RequestField: typeof import('./src/components/RequestField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./src/components/SectionCard.vue')['default']
    StatTiles: typeof import('./src/components/StatTiles.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    TotalRow: typeof import('./src/components/TotalRow.vue')['default']
  }
}
